title: " " 
# show_downloads: true 
description: By <a href="https://reevafaisal.github.io/Portfolio/">Reeva Faisal</a>
# logo: "Screenshot 2024-10-13 at 4.04.46 PM_batcheditor_fotor.jpg" 
github_button: true
# email: reevaf@umich.edu
# repository: https://github.com/reevafaisal/reevafaisal.github.io
# theme: jekyll-theme-minima
favicon: true 
plugins:  
  - jekyll-remote-theme 
  
# plugins:
#   - jekyll-sitemap  
#   - jekyll-seo-tag
#   - jemoji
color-scheme: light

# { scroll: false, shallow: true }
# includes:
#   - assets/js/custom.js

remote_theme: reevafaisal/jekyll-theme-minimal-new

navigation:
  - name: Description
    link: ./index.html#description
  - name: Key Features
    link: ./index.html#key-features
  - name: Usage Instructions
    link: ./index.html#usage-instructions
  - name: Test Links
    link: ./index.html#test-links
  
